# Generated by Django 3.2 on 2021-05-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del item', max_length=150, verbose_name='Nombre')),
                ('sku', models.CharField(help_text='Codigo del producto', max_length=20, verbose_name='Codigo')),
                ('description', models.TextField(blank=True, default='', help_text='Descripcion del item', verbose_name='Descripcion')),
                ('pvp', models.DecimalField(decimal_places=3, help_text='Precio de venta del item.', max_digits=8, verbose_name='Precio de venta')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
    ]
