# Generated by Django 3.2 on 2021-05-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto principal del producto', null=True, upload_to='item', verbose_name='Imagen'),
        ),
    ]
