# Generated by Django 3.2 on 2021-05-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0003_auto_20210514_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo de la orden', max_length=80, unique=True, verbose_name='Codigo')),
                ('firs_name', models.CharField(help_text='Nombres del cliente', max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(help_text='Apellidos del cliente', max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dni', models.CharField(max_length=20, verbose_name='No. Identificación')),
                ('city', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, default='', max_length=30, verbose_name='Codigo postal')),
                ('paid', models.BooleanField(default=False, verbose_name='Es pagada')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalogue.itemmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordermodel')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'db_table': 'order_item',
            },
        ),
    ]
