# Generated by Django 3.2 on 2021-05-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(default='', help_text='Dirección', max_length=200, verbose_name='Dirección'),
        ),
    ]
